#设置项目端口
server:
  version: v.0.0.1.dev.20211018.1026

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hitit?museUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  # File upload size
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 200MB

  # Flyway
  flyway:
    validateOnMigrate: true
    baseline-on-migrate: true

# 文件上传下载
file:
  path: d:/hitit



